[package]
name = "l9961"
version = "0.1.0"
authors = ["Zach Heylmun <zheylmun@gmail.com>"]
description = "Driver for the ST L9961 Industrial BMS"
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/zheylmun/stl9961"
readme = "README.md"

[dependencies]
defmt = { version = "0.3", optional = true }
embedded-hal = "1"
embedded-hal-async = { version = "1", optional = true }
maybe-async-cfg = "0.2"

[dev-dependencies]
embedded-hal-async = "1"
defmt = "0.3"

[features]
default = ["defmt"]
defmt = ["dep:defmt"]
async = ["dep:embedded-hal-async"]
